# Generated by Django 5.2.4 on 2025-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
