# Generated by Django 5.2.4 on 2025-10-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0002_remove_sign_up_confirm_password_alter_login_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
