# Generated by Django 5.2.4 on 2025-10-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0003_alter_login_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
