# Generated by Django 5.2.4 on 2025-10-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0004_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField()),
                ('category', models.CharField(max_length=200, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=200)),
                ('school_code', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('reported_by', models.CharField(max_length=100)),
                ('user_role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Administrator'), ('staff', 'Staff'), ('other', 'Other')], default='', max_length=50)),
                ('contact_email', models.EmailField(max_length=50)),
                ('contact_phone', models.IntegerField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
            ],
        ),
    ]
