# Generated by Django 5.2.4 on 2025-10-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0005_create_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='category',
            field=models.CharField(choices=[('hrms', 'HRMS'), ('student', 'Student'), ('teacher', 'Teacher'), ('other', 'Other')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='user_role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('principle', 'Principle'), ('admin', 'Administrator'), ('parent', 'Parent'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
