# Generated by Django 5.2.4 on 2025-10-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0006_alter_create_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='user_role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('principal', 'Principal'), ('admin', 'Administrator'), ('parent', 'Parent'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
