# Generated by Django 5.2.4 on 2025-10-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0007_alter_create_ticket_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
