# Generated by Django 5.2.4 on 2025-10-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0008_alter_create_ticket_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_ticket',
            old_name='category',
            new_name='isuue_scope',
        ),
        migrations.RenameField(
            model_name='create_ticket',
            old_name='sub_category',
            new_name='specific_concern',
        ),
    ]
