# Generated by Django 5.2.4 on 2025-10-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0009_rename_category_create_ticket_isuue_scope_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_ticket',
            old_name='isuue_scope',
            new_name='issue_scope',
        ),
    ]
