# Generated by Django 5.2.4 on 2025-10-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0010_rename_isuue_scope_create_ticket_issue_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_ticket',
            old_name='reported_by',
            new_name='assignment_group',
        ),
        migrations.RenameField(
            model_name='create_ticket',
            old_name='school_code',
            new_name='caller',
        ),
        migrations.RenameField(
            model_name='create_ticket',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='create_ticket',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='issue_scope',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='location',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='specific_concern',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='title',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='user_role',
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('inquiry/help', 'Inquiry/Help'), ('software', 'Software'), ('hardware', 'Hardware'), ('network', 'Network'), ('database', 'Database'), ('other', 'Other')], max_length=100),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], default=''),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='impact',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=''),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='short_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('active', 'Active')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=''),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='watch_list',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='work_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='priority',
            field=models.CharField(choices=[('planning', 'Planning'), ('moderate', 'Moderate'), ('high', 'High')], default=''),
        ),
    ]
