# Generated by Django 5.2.4 on 2025-10-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0011_rename_reported_by_create_ticket_assignment_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_ticket',
            old_name='created',
            new_name='created_at',
        ),
    ]
