# Generated by Django 5.2.4 on 2025-10-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0012_rename_created_create_ticket_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_ticket',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
