# Generated by Django 5.2.4 on 2025-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0013_rename_updated_create_ticket_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
