# Generated by Django 5.2.4 on 2025-10-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0014_alter_create_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('inquiry/help', 'Inquiry/Help'), ('software', 'Software'), ('hardware', 'Hardware'), ('network', 'Network'), ('database', 'Database'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('active', 'Active')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='watch_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='work_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
