# Generated by Django 5.2.4 on 2025-10-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0015_alter_create_ticket_additional_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ticket',
            name='watch_list',
        ),
    ]
