# Generated by Django 5.2.4 on 2025-10-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0016_remove_create_ticket_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('planning', 'Planning'), ('moderate', 'Moderate'), ('high', 'High')], default='', null=True),
        ),
    ]
