# Generated by Django 5.2.4 on 2025-10-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0017_alter_create_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], default='email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='impact',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=100),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('planning', 'Planning'), ('moderate', 'Moderate'), ('high', 'High')], default='planning', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=100),
        ),
    ]
