# Generated by Django 5.2.4 on 2025-10-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0018_alter_create_ticket_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ticket',
            name='school_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
