# Generated by Django 5.2.4 on 2025-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0019_create_ticket_school_code_create_ticket_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('self-service', 'Self-service'), ('chat', 'Chat'), ('virtual agent', 'Virtual Agent'), ('walk-in', 'Walk-in'), ('other', 'Other')], default='email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in progress', 'In Progress'), ('on hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='', max_length=100, null=True),
        ),
    ]
