# Generated by Django 5.2.4 on 2025-10-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0020_alter_create_ticket_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('anti-virus', 'Anti-virus'), ('email', 'Email'), ('internet application', 'Internet application'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
