# Generated by Django 5.2.4 on 2025-10-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0021_alter_create_ticket_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('anti-virus', 'Anti-virus'), ('email', 'Email'), ('internal application', 'Internal application'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
