# Generated by Django 5.2.4 on 2025-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0022_alter_create_ticket_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
