# Generated by Django 5.2.4 on 2025-11-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0023_assignment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_group',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment_group',
            name='group_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_group',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_group',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
