# Generated by Django 5.2.4 on 2025-11-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0026_alter_activity_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='assignment_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
