# Generated by Django 5.2.4 on 2025-11-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0027_alter_create_ticket_assignment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
