# Generated by Django 5.2.4 on 2025-11-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0028_activity_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='new_values',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='old_values',
        ),
        migrations.AddField(
            model_name='activity',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(default='Fields changed', max_length=100),
        ),
    ]
