# Generated by Django 5.2.4 on 2025-11-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0029_remove_activity_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='changes',
        ),
        migrations.CreateModel(
            name='Activity_Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_values', models.TextField(blank=True, null=True)),
                ('new_values', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='servicedeskapp.activity')),
            ],
        ),
    ]
