# Generated by Django 5.2.4 on 2025-11-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0030_remove_activity_changes_activity_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='new_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='old_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Activity_Change',
        ),
    ]
