# Generated by Django 5.2.4 on 2025-11-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0031_activity_new_values_activity_old_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='new_values',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='old_values',
        ),
        migrations.CreateModel(
            name='Field_Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('actitvity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='servicedeskapp.activity')),
            ],
        ),
    ]
