# Generated by Django 5.2.4 on 2025-11-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0032_remove_activity_new_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field_change',
            old_name='actitvity',
            new_name='activity',
        ),
    ]
