# Generated by Django 5.2.4 on 2025-11-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0034_alter_assignment_group_description_group_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_members',
            old_name='names',
            new_name='name',
        ),
    ]
