# Generated by Django 5.2.4 on 2025-11-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0035_rename_names_group_members_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('other', 'Other')], default='user', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
