# Generated by Django 5.2.4 on 2025-11-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0052_alter_user_management_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='role',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=100, null=True),
        ),
    ]
