# Generated by Django 5.2.4 on 2025-11-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0057_assignment_group_username_alter_user_management_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_group',
            name='username',
        ),
        migrations.AddField(
            model_name='user_management',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_management',
            name='role',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=100, null=True),
        ),
    ]
