# Generated by Django 5.2.4 on 2025-11-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0061_alter_user_management_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('other', 'Other')], default='user', max_length=100, null=True),
        ),
    ]
