# Generated by Django 5.2.4 on 2025-11-13 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0082_alter_user_management_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and contain only numbers.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user_management',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('other', 'Other')], default='user', max_length=100, null=True),
        ),
    ]
