# Generated by Django 5.2.4 on 2025-11-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0083_alter_user_management_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='role',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=100, null=True),
        ),
    ]
