# Generated by Django 5.2.4 on 2025-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0089_alter_user_management_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('other', 'Other'), ('user', 'User')], default='user', max_length=100, null=True),
        ),
    ]
