# Generated by Django 5.2.4 on 2025-11-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0092_master_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ticket',
            name='caller_category',
            field=models.CharField(blank=True, choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('office staff', 'Office staff'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
