# Generated by Django 5.2.4 on 2025-11-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0093_create_ticket_caller_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_members',
            name='name',
        ),
        migrations.AddField(
            model_name='group_members',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicedeskapp.user_management'),
        ),
    ]
