# Generated by Django 5.2.4 on 2025-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0094_remove_group_members_name_group_members_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
