# Generated by Django 5.2.4 on 2025-12-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0096_caller_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller_details',
            name='school_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caller_details',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
