# Generated by Django 5.2.4 on 2025-12-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0097_caller_details_school_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ticket',
            name='caller_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicedeskapp.caller_details'),
        ),
    ]
