# Generated by Django 5.2.4 on 2025-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0098_create_ticket_caller_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ticket',
            name='caller_details',
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='caller_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='caller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
