# Generated by Django 5.2.4 on 2025-12-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0099_remove_create_ticket_caller_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caller_details',
            old_name='email',
            new_name='caller_email',
        ),
        migrations.RenameField(
            model_name='caller_details',
            old_name='name',
            new_name='caller_name',
        ),
        migrations.RenameField(
            model_name='caller_details',
            old_name='phone',
            new_name='caller_phone',
        ),
        migrations.RenameField(
            model_name='caller_details',
            old_name='role',
            new_name='caller_role',
        ),
    ]
