# Generated by Django 5.2.4 on 2025-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0100_rename_email_caller_details_caller_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ticket',
            name='caller_category',
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='platform',
            field=models.CharField(blank=True, choices=[('web application', 'Web Application'), ('mobile application', 'Mobile Application')], max_length=100, null=True),
        ),
    ]
