# Generated by Django 5.2.4 on 2025-12-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0101_remove_create_ticket_caller_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ticket',
            name='caller_email',
        ),
        migrations.RemoveField(
            model_name='create_ticket',
            name='caller_id',
        ),
    ]
