# Generated by Django 5.2.4 on 2025-12-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0102_remove_create_ticket_caller_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicedeskapp.caller_details'),
        ),
    ]
