# Generated by Django 5.2.4 on 2025-12-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0103_alter_create_ticket_caller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='caller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
