# Generated by Django 5.2.4 on 2025-12-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0104_alter_create_ticket_caller'),
    ]

    operations = [
    ]
