# Generated by Django 5.2.4 on 2025-12-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0105_add_caller_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ticket',
            name='caller_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='servicedeskapp.caller_details'),
        ),
    ]
