# Generated by Django 5.2.4 on 2025-12-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0106_create_ticket_caller_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days'), ('minutes', 'Minutes')], max_length=50, null=True)),
            ],
        ),
    ]
