# Generated by Django 5.2.4 on 2025-12-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0107_priority_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicedeskapp.priority_data'),
        ),
    ]
