# Generated by Django 5.2.4 on 2025-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0108_alter_create_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='priority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
