# Generated by Django 5.2.4 on 2025-12-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0110_alter_create_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority_data',
            name='name',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=100, null=True),
        ),
    ]
