# Generated by Django 5.2.4 on 2025-12-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0111_alter_priority_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ticket',
            name='sla_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
