# Generated by Django 5.2.4 on 2025-12-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0112_create_ticket_sla_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_ticket',
            name='sla_due',
        ),
    ]
