# Generated by Django 5.2.4 on 2025-12-16 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0113_remove_create_ticket_sla_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('opened_time', models.DateTimeField(blank=True, null=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('tickte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='servicedeskapp.create_ticket')),
            ],
        ),
    ]
