# Generated by Django 5.2.4 on 2025-12-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0114_ticket_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_duration',
            old_name='tickte',
            new_name='ticket',
        ),
    ]
