# Generated by Django 5.2.4 on 2025-12-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0115_rename_tickte_ticket_duration_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_duration',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
