# Generated by Django 5.2.4 on 2025-12-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0117_alter_ticket_duration_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_duration',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
