# Generated by Django 5.2.4 on 2025-12-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0118_alter_ticket_duration_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_duration',
            name='modules',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
