# Generated by Django 5.2.4 on 2025-12-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0119_ticket_duration_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ticket',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
