# Generated by Django 5.2.4 on 2025-12-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0120_create_ticket_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
