# Generated by Django 5.2.4 on 2025-12-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0121_create_ticket_resolved_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_ticket',
            old_name='sub_category',
            new_name='modules',
        ),
    ]
