# Generated by Django 5.2.4 on 2025-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0122_rename_sub_category_create_ticket_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ticket',
            name='caused_by_change',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='change_request',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='parent_incident',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='problem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='create_ticket',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
