# Generated by Django 5.2.4 on 2025-12-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0124_category_modules_alter_create_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='category',
            field=models.CharField(blank=True, choices=[('inquiry/help', 'Inquiry/Help'), ('software', 'Software'), ('hardware', 'Hardware'), ('network', 'Network'), ('database', 'Database'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket',
            name='modules',
            field=models.CharField(blank=True, choices=[('anti-virus', 'Anti-virus'), ('email', 'Email'), ('internal application', 'Internal application'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
