# Generated by Django 5.2.4 on 2025-12-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0125_alter_create_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_ticket',
            name='modules',
            field=models.CharField(blank=True, choices=[('hrms', 'HRMS'), ('admin', 'Admin'), ('fee', 'Fee'), ('teacher', 'Teacher'), ('transport', 'Transport'), ('library', 'Library'), ('asset management', 'Asset Management'), ('application tracker', 'Application Tracker'), ('store', 'Store'), ('visitor management', 'Visitor Management')], max_length=100, null=True),
        ),
    ]
