# Generated by Django 5.2.4 on 2025-12-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedeskapp', '0127_alter_create_ticket_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_ticket',
            name='resolution_code',
            field=models.CharField(choices=[('duplicate', 'Duplicate'), ('known error', 'Known error'), ('no resolution provided', 'No resolution provided'), ('resolved by caller', 'Resolved by caller'), ('resolved by change', 'Resolved by change'), ('resolved by problem', 'Resolved by problem'), ('resolved by request', 'Resolved by request'), ('solution provided', 'Solution Provided'), ('workaround provided', 'Workaround provided'), ('user error', 'User error')], default='duplicate', max_length=100),
        ),
    ]
